# Generated by Django 5.2.1 on 2025-06-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
