# Generated by Django 5.2.1 on 2025-06-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
