# Generated by Django 5.2.1 on 2025-06-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_leavetype_leavesummary_leaveapproval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='attachment_path',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='leave_attachments/'),
        ),
    ]
