# Generated by Django 5.2.1 on 2025-06-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_leaverequest_attachment_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='days',
            field=models.PositiveIntegerField(),
        ),
    ]
