# Generated by Django 5.2.1 on 2025-06-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_leaverequest_rejection_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='rejection_reason',
            new_name='note',
        ),
    ]
