# Generated by Django 5.2.1 on 2025-06-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_rejection_reason_leaverequest_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField()),
                ('holiday_name', models.CharField(max_length=100)),
                ('holiday_type', models.CharField(choices=[('Public Holiday', 'Public Holiday'), ('Company Birthday', 'Company Birthday'), ('Company Holiday', 'Company Holiday')], max_length=50)),
            ],
        ),
    ]
