# Generated by Django 4.2.4 on 2025-06-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_event_day'),
        ('api', '0009_event'),
    ]

    operations = [
    ]
