# Generated by Django 5.2.1 on 2025-06-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_event_day'),
        ('api', '0009_event'),
    ]

    operations = [
    ]
