# Generated by Django 5.2.1 on 2025-06-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveSetting',
            fields=[
                ('working_hours_start', models.TimeField(default='09:00')),
                ('working_hours_end', models.TimeField(default='17:00')),
                ('is_flexible_hours_enabled', models.BooleanField(default=False)),
                ('is_weekday_workday', models.BooleanField(default=True)),
                ('is_weekend_workday', models.BooleanField(default=False)),
                ('cycle_type', models.CharField(default='annual', max_length=20)),
                ('singleton_id', models.PositiveIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='leavesummary',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='leavesummary',
            name='request',
        ),
        migrations.RemoveField(
            model_name='leavesummary',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='leavesummary',
            name='user',
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='LeaveApproval',
        ),
        migrations.DeleteModel(
            name='LeaveSummary',
        ),
    ]
