# Generated by Django 4.2.4 on 2025-06-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_leavesetting_remove_leavesummary_leave_type_and_more'),
        ('api', '0010_merge_0004_alter_event_day_0009_event'),
    ]

    operations = [
    ]
